[package]
name = "print_struct"
version = "0.1.0"
authors = ["Gabriel Koutilellis <gkoutilellis@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
